MikkoTirronen/backend2-realworld

app.js
=> Zamir added comments

models/article.js
Created article model in models folder
=> Added article model

models/article.js
=> Small fix modell

app.js, models/article.js
Small steps to render articles, not there yet
=> Get my articles

app.js, models/article.js
=> Added slug

app.js
=> Render Articles

app.js, models/user.js
=> Changed Body/Model

app.js, models/article.js
=> Added popular tags

app.js
=> Token on login

app.js
Added query params to search with req.query
=> Added query params

app.js
Updated log in to save new token in MongoDB and send it to front end
=> New token on log in updated

app.js
Added Get User so we can stay logged in
=> Added Get User

app.js, controllers/articles.js, controllers/tags.js
=> moved tags to controllers

app.js, controllers/slug.js
=> Moved slug to controllers

app.js, controllers/GETslug.js, controllers/GETuser.js, controllers/POSTuser.js
=> More routes

app.js, controllers/POSTarticles.js
=> post article route

app.js, controllers/PUTuser.js
=> All routes

app.js, controllers/DELETEfavorite.js, controllers/GETarticles.js, controllers/GETprofile.js, controllers/GETuser.js, controllers/POSTfavorite.js, controllers/PUTuser.js
=> Added favorites

app.js, controllers/DELETEfavorite.js, controllers/GETarticles.js, controllers/POSTfavorite.js
=> article by author

controllers/PUTarticles.js
Timestamp updates when updating article
=> Timestamp updates when updating article

app.js, controllers/DELETEfavorite.js, controllers/GETarticles.js, controllers/POSTfavorite.js, controllers/PUTarticles.js, models/article.js
Fixed favorites, though some bugs when changing user, tests are OK
=> Fixed favorites

controllers/PUTarticles.js, controllers/PUTuser.js
Fixed PUT-user bug, it sent empty body for update, now PUT-user-test works
=> Fixed PUT-user

controllers/PUTarticles.js
Fixed PUT-article, missing is tags
=> Fixed Put article

controllers/GETarticles.js, controllers/PUTarticles.js
=> Fixed update tags

controllers/DELETEfavorite.js, controllers/GETarticles.js, controllers/POSTfavorite.js, controllers/PUTarticles.js
Found one bug in favorite, though problem still there when changing user...
=> Found one bug favorite
